/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface Event {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'description' : string,
  'registrationLink' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface StrayDogImage {
  'description' : string,
  'timestamp' : Time,
  'image' : ExternalBlob,
  'location' : string,
  'uploadedBy' : string,
}
export type Time = bigint;
export interface User {
  'name' : string,
  'email' : string,
  'phone' : string,
  'location' : string,
  'vaccinationCentre' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addEvent' : ActorMethod<[string, Time, string, string, string], undefined>,
  'addProduct' : ActorMethod<[string, string, bigint, ExternalBlob], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllStrayDogImages' : ActorMethod<[], Array<StrayDogImage>>,
  'getUser' : ActorMethod<[Principal], User>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'sendMessage' : ActorMethod<[string], undefined>,
  'uploadStrayDogImage' : ActorMethod<
    [ExternalBlob, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];